### ISSUE TITLE
[melodic-devel branch] Remove/update location lines from vizzy_navigation/CMakeLists.txt

### ISSUE THREAD

**Issue by plinioMoreno** [vislab-tecnico-lisboa/vizzy#125]
The launchers of deprecated move_base need to be removed/updated (melodic-devel branch)

https://github.com/vislab-tecnico-lisboa/vizzy/blob/melodic-devel/vizzy_navigation/CMakeLists.txt#L148

**Comment by joao-avelino** [comment]
Solved on 5bdc17ae7e3f68ddf217db1c9eca32169ee054d1 . I merged all the fixes of master into melodic-devel.
