### ISSUE TITLE
Need to install OpenCV for cameras usage

### ISSUE THREAD

**Issue by mikearagao** [vislab-tecnico-lisboa/vizzy#38]
@aba92 please start posting your issues on this repository... We will delete the old ones soon :smile:

**Comment by mikearagao** [comment]
Not sure about this... I've only performed the most basic actions with the cameras and I don't have OpenCV installed on my system. Maybe @plinioMoreno and @ruipimentelfigueiredo can give better feedback on this! :+1:

**Comment by ruipimentelfigueiredo** [comment]
Hi @aba92. In principe you don't need to install opencv in order to use vizzy in gazebo. However if you intend to do some image processing, for sure you will need it. By doing rosdep install vizzy_package_name your telling your ubuntu OS to install all the needed dependencies via apt-get. If you done that you should be fine. If you are interested in knowing the vizzy packages dependencies, please check their package.xml and CMakeLists.txt files. I've noticed that the package vizzy_yarp_icub needs opencv. But as far as I know this one is ROS independent. @mikearagao and @plinioMoreno please correct me if I'm wrong

**Comment by aba92** [comment]
So probably i'll need to install it, since i'll have to do some image processing. Thank you. :)

**Comment by plinioMoreno** [comment]
Hi Aba,

 From what we talked with Prof. Alexandre, I think you need to install 
OpenCV. But you can install the package that is integrated within ROS, 
which is the easiest way of doing it and works most of the times.


On 3/6/2015 5:42 PM, aba92 wrote:
>
> So probably i'll need to install it, since i'll have to do some image 
> processing. Thank you. :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vislab-tecnico-lisboa/vizzy/issues/38#issuecomment-77601638>.
>

-- 
___________________

Plinio Moreno López
http://www.isr.ist.utl.pt/~plinio
plinio@isr.tecnico.ulisboa.pt
___________________

**Comment by plinioMoreno** [comment]
Very good explanation @ruipimentelfigueiredo!

On 3/6/2015 5:16 PM, Rui Miguel Horta Pimentel de Figueiredo wrote:
>
> Hi @aba92 <https://github.com/aba92>. In principe you don't need to 
> install opencv in order to use vizzy in gazebo. However if you intend 
> to do some image processing, for sure you will need it. By doing 
> rosdep install vizzy_package_name your telling your ubuntu OS to 
> install all the needed dependencies via apt-get. If you done that you 
> should be fine. If you are interested in knowing the vizzy packages 
> dependencies, please check their package.xml and CMakeLists.txt files. 
> I've noticed that the package vizzy_yarp_icub needs opencv. But as far 
> as I know this one is ROS independent. @mikearagao 
> <https://github.com/mikearagao> and @plinioMoreno 
> <https://github.com/plinioMoreno> please correct me if I'm wrong
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vislab-tecnico-lisboa/vizzy/issues/38#issuecomment-77597040>.
>

-- 
___________________

Plinio Moreno López
http://www.isr.ist.utl.pt/~plinio
plinio@isr.tecnico.ulisboa.pt
___________________

**Comment by aba92** [comment]
@plinioMoreno are you talking about vision_opencv package? But it is not just a bridge between ros and openCV? In other words, it works without openCV?

**Comment by ruipimentelfigueiredo** [comment]
@aba92 yes. After ROS groovy (if i recall correctly) ROS started using the
opencv that comes with your OS. And yes, vision_opencv and cv_brigde are
just packages for interfacing ROS with opencv.

**Comment by aba92** [comment]
Thank you @ruipimentelfigueiredo

**Comment by mikearagao** [comment]
@aba92 closing this issue. Feel free to open it in case you need more help!
