### ISSUE TITLE
Error on running vizzy_simulation.launch when the flag use_yarp:=true

### ISSUE THREAD

**Issue by pedrommarques** [vislab-tecnico-lisboa/vizzy#39]
After downloading the content of the whole Vizzy repository, when I tried to run, I got the following error
##
$ roslaunch vizzy_launch vizzy_simulation.launch use_yarp:=true navigation:=true

< a lot of stuff and then the error >
roslaunch.substitution_args.ArgException: use_yarp
while processing /home/pedro/catworkspace/src/vizzy-master/vizzy_moveit_config/launch/moveit.launch:
while processing /home/pedro/catworkspace/src/vizzy-master/vizzy_moveit_config/launch/planning_context.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/hydro/share/xacro/xacro.py '/home/pedro/catworkspace/src/vizzy-master/vizzy_description/robots/vizzy.urdf.xacro'] returned with code [1]. 

Param xml is < param command="$(find xacro)/xacro.py '$(find vizzy_description)/robots/vizzy.urdf.xacro'" if="$(arg load_robot_description)" name="$(arg robot_description)"/>
##

> It seems that the file vizzy-master/vizzy_moveit_config/launch/planning_context.launch is incomplete.

**Comment by plinioMoreno** [comment]
Hi @pedrommarques,

please change one of the flags to use_yarp:=false and try it again. I just tested and it is working properly. The only errors that you should see are as follows:

Error [Param.cc:181] Unable to set value [1,0471975511965976] for key[horizontal_fov]
Error [Param.cc:181] Unable to set value [0,100000001] for key[near]

On the rviz interface, you should be able to see the left and right camera.

**Comment by pedrommarques** [comment]
Even with use_yarp:=false , i still get a similar error:

roslaunch.substitution_args.ArgException: use_yarp
while processing /home/pedro/catworkspace/src/vizzy-master/vizzy_moveit_config/launch/moveit.launch:
while processing /home/pedro/catworkspace/src/vizzy-master/vizzy_moveit_config/launch/planning_context.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/hydro/share/xacro/xacro.py '/home/pedro/catworkspace/src/vizzy-master/vizzy_description/robots/vizzy.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find vizzy_description)/robots/vizzy.urdf.xacro'" if="$(arg load_robot_description)" name="$(arg robot_description)"/>

**Comment by ruipimentelfigueiredo** [comment]
Hi @pedrommarques,

First of all welcome to the vizzy development github repository!

My first guess is that you don't have moveit installed on your PC. Recently we integrated moveit in vizzy. 

Please install the missing dependencies with the following command rosdep install vizzy_moveit_config. This should work out. If it does not and assuming you are using Indigo, please install it with the following command: sudo apt-get install ros-indigo-moveit*

**Comment by pedrommarques** [comment]
You were right @ruipimentelfigueiredo , I did not have moveit installed. But I do now, and the error remains exactly the same, with yarp:=false or true .

**Comment by plinioMoreno** [comment]
Hi @pedrommarques ,

from the ouput:

"Invalid tag: Cannot load command parameter [robot_description]: command [/opt/ros/hydro/share/xacro/xacro.py '/home/pedro/catworkspace/src/vizzy-master/vizzy_description/robots/vizzy.urdf.xacro'] returned with code [1]."

It looks like you have set the ROS "hydro" version as the running one (because the xacro.py is from that version). Is that correct? If this is the case, please ensure that "indigo" is the running version. The packages work only in ROS indigo.

I would suggest to check which setup.bash is being called. (for instance "source /opt/ros/<ros version>/setup.sh", where <ros version> must be indigo and I guess right now it is "hydro").

**Comment by pedrommarques** [comment]
That is correct @plinioMoreno . My current ROS version is Hydro, since on the readme page it says that it is the only current fully supported ROS release. So I should upgrade to indigo in order to work with this Vizzy package?

**Comment by plinioMoreno** [comment]
There have been developments after @mikearagao left. I would suggest to upgrade to indigo and try it again. If it does not work, we can meet to see what is happening.
