### ISSUE TITLE
Fixation point and ball position (from yarp to ROS)

### ISSUE THREAD

**Issue by ruipimentelfigueiredo** [vislab-tecnico-lisboa/vizzy#42]
We should use Miguel Aragão's master thesis work to send vizzy's current fixation point  (provided by the Ikin gaze controller) and the ball position (provided by Matteo's ball tracker) to ROS side, for visualization purposes.

**Comment by plinioMoreno** [comment]
Commit 2de8fdbf5dc70ca5f57f554f258776d03eb28d10 adds the first version of the automatically generated code. The current version of the bridges were created using [the yarp-bottle-generator](https://github.com/vislab-tecnico-lisboa/yarp-bottle-generator/commit/42c97eaedf7361504466f7585dd360edba801d18)
