### ISSUE TITLE
Finish ROS/YARP motor command, hardwired interfaces

### ISSUE THREAD

**Issue by ruipimentelfigueiredo** [vislab-tecnico-lisboa/vizzy#47]

**Comment by plinioMoreno** [comment]
Implementing this interfaces requires a large low-level code that will take too long to implement, so bridges between YARP and ROS are begin implemented currently (e.g. the [follow trajectory bridge](https://github.com/vislab-tecnico-lisboa/vizzy/blob/master/vizzy_yarp_icub/src/modules/motorInterfaceFromRos/follow_trajectory_action_bridge.cpp) for moveit.
