### ISSUE TITLE
Vizzy manual and documentation

### ISSUE THREAD

**Issue by gsaponaro** [vislab-tecnico-lisboa/vizzy#52]
Hi @plinioMoreno (+ @ruipimentelfigueiredo @joao-avelino),

Last summer, we started copying the documentation of Vizzy on the wiki associated to this repository, here:
https://github.com/vislab-tecnico-lisboa/vizzy/wiki

Personally, I think it would be good to put the remaining documentation (i.e., the PDF manual) on the wiki too, in order to (1) have it all in one place, (2) make it easily and quickly updatable in the browser, (3) facilitate the transition of knowledge if some of you ever leave the lab (I hope not! but just in case :) ).

Furthermore, it will still be possible to generate printable PDFs (from GitHub wiki Markdown syntax) by using tools like this one: https://www.npmjs.com/package/markdown-pdf

**Comment by plinioMoreno** [comment]
The source of the manual ( which is outdated ) is on the vislablisboa google drive account. I just shared the document with you, and in the near future we can copy the text and update the manual in the wiki.

**Comment by gsaponaro** [comment]
Cool, thanks. I want to help with both things (updating and copying/moving the text). It is not necessary for the text to be perfect in order to do the copying - we can do the improvements incrementally. In any case, tomorrow we can talk about it.

PS: some of the issues at https://github.com/vislab-tecnico-lisboa/vizzy/issues can probably be closed due to being outdated too.

**Comment by gsaponaro** [comment]
The "How to start Vizzy up" manual has now been ported here:

https://github.com/vislab-tecnico-lisboa/vizzy/wiki/How-to-start-Vizzy-up

**Comment by plinioMoreno** [comment]
Thanks @gsaponaro !! It looks very good. I'll start doing updates to the manual during this week

**Comment by gsaponaro** [comment]
Hi @plinioMoreno, as discussed face to face, I have now removed the old Google document "How to start Vizzy up", in favour of the wiki page https://github.com/vislab-tecnico-lisboa/vizzy/wiki/How-to-start-Vizzy-up which contains all the old Google Doc content + some recent addition from two weeks ago by @joao-avelino. Closing this issue.
