### ISSUE TITLE
Change local planner

### ISSUE THREAD

**Issue by joao-avelino** [vislab-tecnico-lisboa/vizzy#53]
Update the local planner from the eband (Elastic Band) local planner to the teb_local_planner (Timed Elastic Band)

**Comment by ruipimentelfigueiredo** [comment]
@joao-avelino Regarding the global planner. Have you seen this one http://wiki.ros.org/global_planner ?

**Comment by joao-avelino** [comment]
Addressed on @ #118 . Thanks @ruipimentelfigueiredo for global planner indication.

Once someone accepts tests it and accepts the pull request we can close this issue.
