### ISSUE TITLE
[Vizzy simulation] incorrect camera frame id

### ISSUE THREAD

**Issue by joao-avelino** [vislab-tecnico-lisboa/vizzy#57]
The camera frame_id published on the camera_info topic is incorrect. The correct one should be "*_camera_vision_link" instead of  "*_camera_link".

**Comment by jsbruglie** [comment]
@joao-avelino Is [this](https://github.com/vislab-tecnico-lisboa/vizzy/blob/2ac3533aa90d2056459109fa2f91fc76be196d47/vizzy_description/plugins/ros.gazebo.xacro#L105) what you mean?
