### ISSUE TITLE
[Vizzy real/laptop] Time synchronization

### ISSUE THREAD

**Issue by joao-avelino** [vislab-tecnico-lisboa/vizzy#58]
If the clocks on Vizzy and a networked device (laptop for instance) are not synchronized tf's throw an exception.

The solution is here: http://wiki.ros.org/ROS/NetworkSetup#Timing_issues.2C_TF_complaining_about_extrapolation_into_the_future.3F

**Comment by plinioMoreno** [comment]
Moved to the [troubleshooting guide section](https://github.com/vislab-tecnico-lisboa/vizzy/wiki/How-to-start-Vizzy-up#troubleshooting) of How to start Vizzy, thanks @joao-avelino for the information
