### ISSUE TITLE
Select and purchase new cameras

### ISSUE THREAD

**Issue by plinioMoreno** [vislab-tecnico-lisboa/vizzy#71]
Search for new cameras that fit in the eyes @rnun3s @plinioMoreno

**Comment by gsaponaro** [comment]
Out of curiosity, what was the final decision on this? E.g., model name.

**Comment by rnun3s** [comment]
**Brand:** IDS
**Model:** UI-3881LE
**Specs:** USB 3.1, CMOS, 58.7 fps, 3088 x 2076, 6.41 MPix, 1/1.8" Sony, Rolling Shutter
