### ISSUE TITLE
Removing Old/New files of arm Gesture

### ISSUE THREAD

**Issue by vicentepedro** [vislab-tecnico-lisboa/vizzy#75]
Hi @joao-avelino 

Can you check if it makes sense to maintain these files on the repo:

`/vizzy_yarp_icub/src/modules/armGesture/src/vizzyArmRoutines.cpp_new`
`/vizzy_yarp_icub/src/modules/armGesture/include/vizzyArmRoutines.h_new`

If I remember correctly, this was the first attempt to change the arm gesture module by J. Salvado.

Best,
Pedro

**Comment by joao-avelino** [comment]
Yeah. Those can be deleted.

Em 16/01/2018 4:02 da tarde, "vicentepedro" <notifications@github.com>
escreveu:
