### ISSUE TITLE
Fake localization node does not work with move_base

### ISSUE THREAD

**Issue by plinioMoreno** [vislab-tecnico-lisboa/vizzy#77]
Since the recent update to ros-kinetic, the fake localization node does not work as expected with the move_base navigation. The robot goes through the obstacles and gets stuck at some point.

Now the default is the amcl, as set in 4fefae18aaec05578e1692b2506b38c38ef81738, and performs similar to the real robot
@joao-avelino @ruipimentelfigueiredo

**Comment by plinioMoreno** [comment]
This issue is related to the fact that the odometry was not computed properly. Commit cac2f3ce7179535765969c6b60f1e0121cfeb3d1 by @joao-avelino alleviates the problem, and now fake localization works well for small values of velocity.

**Comment by joao-avelino** [comment]
#117 solved this problem.

**Comment by plinioMoreno** [comment]
Thanks @joao-avelino !
